# Generated by Django 3.1.7 on 2022-04-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efarma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='nirtogen',
            new_name='nitrogen',
        ),
    ]
